### ISSUE TITLE
New Mojo for Build Execution Graph

### ISSUE THREAD

**Issue by ferstl** [ferstl/depgraph-maven-plugin#103]
Add a Mojo to create an "execution graph" of a multi-module project. Such graphs can show how the Build of a multi-module project can be parallelized.

Algorithm to create the execution graph:
- Loop over the reactor (via MavenSession)
  - Create an edge from the current project to all "downstream" projects
  - If there is already an edge to one of the current "downstram" projects, remove it (keep the longest path to it)

See also: https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3

**Comment by delanym** [comment]
How is this coming along?

**Comment by ferstl** [comment]
This is a bit more complicated than I originally thought. And there is not much time to work on that at the moment.

**Comment by ferstl** [comment]
Version 4.0.0 will be on Maven Central soon.

**Comment by delanym** [comment]
I've tested this and it works to show the module structure of a project, but its not an execution graph. In a multi-threaded build the order of execution is something only known after it has occurred. This can be seen using the opentelemetry-maven-extension and examining the results in Jaeger/Zipkin etc. It will show where threads were not being maximized and which module(s) were holding things up.

The build order Maven gives at the start of the reactor log is a simplified [directed acyclic graph](https://en.wikipedia.org/wiki/Directed_acyclic_graph). This list is unaffected by the number of threads.
For this plugin though, I would like to see a goal that produces a complete DAG of the build. This will show when a given module MUST be executed before any other module. This is different to the current reactor goal's graph because it considers the dependencies which do affect the build order. It will also by necessity work out any cyclic dependencies.
