### ISSUE TITLE
The tree generation can't succeed due to unresolved dependencies. 

### ISSUE THREAD

**Issue by viktigpetterr** [ferstl/depgraph-maven-plugin#116]
I'm trying out your great plugin on https://github.com/neo4j/neo4j but I'm not able to get the tree generation work. 
It fails because of the thrown exception that comes due to unresolved dependencies in `MavenGraphAdapter.buildDependencyGraph()`:
```
    DependencyResolutionResult result;
    try {
      result = this.dependenciesResolver.resolve(request);
    } catch (DependencyResolutionException e) {
      throw new DependencyGraphException(e);
    }
```
You can replicate the issue by just running `mvn com.github.ferstl:depgraph-maven-plugin:graph` on the root pom in the repo above. 
Do you have a clue what the error might be? I'll gladly help you if you point me in the right direction :smile:

**Comment by ferstl** [comment]
Hi,
The problem here is that "Neo4j - Common" has a dependency to "Neo4j - Annotation processors" which is in the Maven reactor but has not produced a build artifact (i.e. JAR file) when only the dependency graph is built. I am not sure if this can be fixed. But as a workaround you could simply add the package goal to the maven command: `mvn package com.github.ferstl:depgraph-maven-plugin:graph` . This will produce build artifacts which the depgraph plugin can use later on during the build.

**Comment by ferstl** [comment]
**Update:** Actually, it is sufficient to add `test-compile` instead of `package` to the graph build.
If Neo4J did not create test JARs for the subsequent modules, adding `compile` would be sufficient.

**Comment by viktigpetterr** [comment]
Hi,
sry for the late answer and ty for the explanation, now it works like a charm! :slightly_smiling_face:
