### ISSUE TITLE
How can I get only root module's dependencies when use -outputDirectory

### ISSUE THREAD

**Issue by Melody618** [ferstl/depgraph-maven-plugin#128]
I use this project https://github.com/mokarakaya/spring-boot-multi-module-maven.

If I run command
 `mvn com.github.ferstl:depgraph-maven-plugin:graph -DgraphFormat=text -DshowDuplicates -DshowConflicts -DshowVersions -DshowGroupIds` 
in path spring-boot-multi-module-maven/, I will get three target folder in spring-boot-multi-module-maven/, spring-boot-multi-module-maven/api/ and spring-boot-multi-module-maven/web/ separately. And the spring-boot-multi-module-maven/target/dependency-graph.txt shows:

> webDemo:webDemo:1.0-SNAPSHOT:compile

But if I run command 
`mvn com.github.ferstl:depgraph-maven-plugin:graph -DgraphFormat=text -DshowDuplicates -DshowConflicts -DshowVersions -DshowGroupIds -DoutputDirectory="spring-boot-multi-module-maven/"`,
in path spring-boot-multi-module-maven/. The dependency-graph.txt shows all dependencies of modules but not webdemo only.

how can I get 

> webDemo:webDemo:1.0-SNAPSHOT:compile

when use -outputDirectory at the same time?

Thanks!

**Comment by ferstl** [comment]
Hi @Melody618 

When I run the first command, I get exactly what you describe and what I expect. However, when I run the second command, I get the same result as in the first command but the graph files are now located in a `spring-boot-multi-module-maven`  folder. Their content is the same as in the first run. So the content of `spring-boot-multi-module-maven\spring-boot-multi-module-maven\dependency-graph.txt` is also

```
webDemo:webDemo:1.0-SNAPSHOT:compile
```

That looks to me like the expected behavior or do I miss something?

**Comment by Melody618** [comment]
Thanks for your reply.

I made a mistake in describing the second command. In the second command, `outputDirectory` is the absolute path of `spring-boot-multi-module-maven`, such as `C:/Desktop/spring-boot-multi-module-maven/`. Because I want to put the result `dependency-graph.txt` in a temp folder but not in the project folder. 

Besides,  I also run the relative path `-DoutputDirectory="spring-boot-multi-module-maven/"` and get what you said. Does the inconsistency a problem here?

**Comment by ferstl** [comment]
What happens here (when you use an absolute path) is, that each module will write its dependency graph into the same directory under the same name. So what you see is the dependency graph of the last module in the Maven reactor since the others were overwritten.
To avoid that you can add  `-DuseArtifactIdInFileName=true` when using absolute paths. This will produce different file names and you will see all three dependency graphs in that directory.

**Comment by Melody618** [comment]
Thanks a lot! It really helps.

Another question. What if I only want to get the dependency graph of the parent module, `webdemo` here, and skip the other modules `api` and `web`? That is, only one file in that directory.

**Comment by ferstl** [comment]
> Another question. What if I only want to get the dependency graph of the parent module, webdemo here, and skip the other modules api and web? That is, only one file in that directory.

You can try the following:
- Run Maven with the `-N` (non-recursive) option. This will only build the parent module without the sub-modules.
- Use a `<plugin>` configuration with `<inherited>false</inherited>` as described here: https://maven.apache.org/guides/mini/guide-configuring-plugins.html#Using_the_inherited_Tag_In_Build_Plugins
