### ISSUE TITLE
Follow optional dependencies

### ISSUE THREAD

**Issue by victornoel** [ferstl/depgraph-maven-plugin#13]
Hi,

I'm not sure it is trivial to solve that, but when a dependency of a graphed project has optional dependencies, it seems they are not shown in the generated graph.

We could have an option to show them or not maybe?

**Comment by ferstl** [comment]
Unfortunately, this is not possible because Maven does not resolve optional dependencies of other dependencies. This is exactly definition of optional dependencies as documented [here](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html):

> When A declares B as an optional dependency in its POM, this relationship remains unchanged. Its just like a normal build where Project-B will be added in its classpath.
> ...
> But when another project(Project-X) declares Project-A as a dependency in its POM, the optional dependency takes effect. You'll notice that Project-B is not included in the classpath of Project-X; you will need to declare it directly in your POM in order for B to be included in X's classpath.

The only solution I see is reading the POM files (and their parent POMs, which are tricky to obtain within a mojo) of all dependencies manually and search for optional dependencies. But this is a lot of work with a quite shaky result.

**Comment by victornoel** [comment]
I guess you would need to switch to using directly aether for that (see the [bottom of that page](https://wiki.eclipse.org/Aether/Transitive_Dependency_Resolution) where it says it is possible).

By the way using aether would also solve the problem of resolving versus simply collection dependencies (see `org.eclipse.aether.RepositorySystem.collectDependencies(RepositorySystemSession, CollectRequest)`).

**Comment by ferstl** [comment]
Oh, didn't know that. I may take a look into it but it's low prio for me at the moment. So this will probably take forever ;-)

**Comment by ferstl** [comment]
Took a while but I finally switched to the Aether API (will be in the next release)...
The good news is that it works quite well and creates accurate graphs even when showing duplicates and conflicts.
The not so good news is that I am still not able to solve this issue. Following optional dependencies would require to use the very low-level APIs of Aether. I don't want to do that because I want to use exactly the same code that Maven does when resolving dependencies. Only this way I can be sure to create graphs that reflect exactly the resolved dependencies.

Dependency collection does not deliver enough information to create graphs that the plugin currently can. So I also have to stick with full dependency resolution.

However, I am working on some support for optional dependencies. See #79 for that. If you think there is something missing, feel free to comment. I'll see what I can do.
I'm closing this issue now for the above reasons.

**Comment by victornoel** [comment]
@ferstl great work, thanks :) (even though I haven't used depgraph-maven-plugin for some time ^^)
