### ISSUE TITLE
`aggregate` goals requires modules to be installed in local repo

### ISSUE THREAD

**Issue by abelsromero** [ferstl/depgraph-maven-plugin#20]
First of all, thanks for the plugin, it's great.

Now my question, I guess this is a normal behavior (but annoying nevertheless), but when I run the `aggregate` goal from a parent project it fails unless I have installed the projects before in my local repo.
Is there a way to avoid this?

**Comment by ferstl** [comment]
> First of all, thanks for the plugin, it's great.

Thank you!

> Now my question, I guess this is a normal behavior (but annoying nevertheless), but when I run the aggregate goal from a parent project it fails unless I have installed the projects before in my local repo.
Is there a way to avoid this?

does only require dependency collection (which does not download any JAR files, see requiresDependencyCollection) but not dependency resolution.

The plugin itself does only require dependency collection (which does not download any JAR files, see [requiresDependencyCollection](https://maven.apache.org/developers/mojo-api-specification.html)) but not dependency resolution in the `aggregate` goals. However, the `maven-dependency-tree` library (which is part of the maven core libraries) bypasses this setting and tries to download all dependencies. You can find the code that triggers the download [here](http://grepcode.com/file/repo1.maven.org/maven2/org.apache.maven.shared/maven-dependency-tree/2.1/org/apache/maven/shared/dependency/graph/internal/Maven31DependencyGraphBuilder.java?av=f#85).

This problem was already reported in #8. As described there, the `-nsu` might help a little.

**Comment by abelsromero** [comment]
> However, the maven-dependency-tree library (which is part of the maven core libraries)

I am familiar with this, that's what I said I assumed to be 'normal behavior' :disappointed: 

> This problem was already reported in #8. As described there, the -nsu might help a little.

My project does not have snapshot, so I am forced to install before running the graph. It's sad cause it prevents me from include the documentation generation early in the build pipeline, but _so be it_.

Thanks again for your support.
