### ISSUE TITLE
Can I append groupId into nodes in generated PNG file?

### ISSUE THREAD

**Issue by firen** [ferstl/depgraph-maven-plugin#6]

**Comment by ferstl** [comment]
@firen This is not possible in the current version of the plugin. The nodes are labeled only with the `artifactId` and `version` of the artifact. I omitted the groupId on purpose in order to keep the boxes in the graph as small as possible.
But since the groupId is already available in the generated `.dot` file, I could add a new option to the plugin to show it in the graph.

**Comment by firen** [comment]
Great thank you for considering it.

**Comment by ferstl** [comment]
A new release of the plugin is on its way to Maven Central and should be available in the next few hours.

The new version will have a `showGroupIds` Option in the [graph](https://ferstl.github.io/depgraph-maven-plugin/graph-mojo.html#showGroupIds) and [aggregate](https://ferstl.github.io/depgraph-maven-plugin/aggregate-mojo.html#showGroupIds) goals.

**Comment by firen** [comment]
Great! Can't wait for the new versions. Thanks for fast implementation.
