### ISSUE TITLE
Do not download dependencies?

### ISSUE THREAD

**Issue by victornoel** [ferstl/depgraph-maven-plugin#8]
Hi,

I tried the graph goal in a multi-module project and I was surprised to see depgraph downloading the jar of the dependencies: doesn't it only need the pom file of the dependency to resolve the graph?

Also, since it was in a multi-module project, shouldn't it use the dependencies that are in the multimodule directly instead of downloading them?

**Comment by ferstl** [comment]
I took a look into that issue and unfortunately, there is nothing I can do about it. The depgraph-maven-plugin does only require dependency collection (which does not download any JAR files, see [requiresDependencyCollection](https://maven.apache.org/developers/mojo-api-specification.html)) but not dependency resolution.
However, the plugin uses some [Maven core libraries](https://maven.apache.org/shared/) to create the dependency graph. One of these libraries makes a hard-coded dependency resolution which triggers the download of all dependencies that are not in your local maven repository. You can find the code that triggers the download [here](http://grepcode.com/file/repo1.maven.org/maven2/org.apache.maven.shared/maven-dependency-tree/2.1/org/apache/maven/shared/dependency/graph/internal/Maven31DependencyGraphBuilder.java?av=f#85).

To mitigate the problem you could run Maven with the `-nsu` option (No SNAPSHOT updates). This will prevent downloading SNAPSHOT dependencies all the time when the graph is built, especially the SNAPSHOTs of your multi-module project. Since the `aggregate` goal does only work on the parent POM of your multi-module project, all the child projects are not part of the build. That's the reason why the artifacts of your project are downloaded too.
All non-SNAPSHOT dependencies should only be downloaded once to your local repository (depending on the policies in your `settings.xml`.

**Comment by victornoel** [comment]
Ha! That's what I was afraid of: that it was a maven core library doing...

Well, I created an [issue](https://issues.apache.org/jira/browse/MSHARED-519) at Apache's JIRA in case they can fix it :)

Also maybe this [issue](https://issues.apache.org/jira/browse/MSHARED-491) is also of interest for this problem...

**Comment by sschuberth** [comment]
> One of these libraries makes a hard-coded dependency resolution which triggers the download of all dependencies that are not in your local maven repository. 

Just FYI, the way we solved this in [ORT](https://github.com/oss-review-toolkit/ort)'s [analyzer](https://github.com/oss-review-toolkit/ort#analyzer) is to [fake that the JAR is actually already preset](https://github.com/oss-review-toolkit/ort/pull/3445) in the local Maven repository. And that works rather well 😁

**Comment by victornoel** [comment]
by the way @ferstl the two bugs I was mentioning were fixed in maven-dependency-tree-3.1.0, so it would be great if we could use this version and release a new version of your plugin :) cheer!

**Comment by ferstl** [comment]
Version 4.0.0 will be on Maven Central soon.

**Comment by victornoel** [comment]
thx!
