### ISSUE TITLE
Only show modules that leads to a set of dependencies

### ISSUE THREAD

**Issue by victornoel** [ferstl/depgraph-maven-plugin#9]
Hi,

It would be great when generating the aggregate graph of a multi-module project to ask for all the dependency paths to one or several modules: we would only see the modules that leads to this set of target dependencies.

This would be very useful as a way to explore the architecture of a multi-module project in localised ways.

**Comment by ferstl** [comment]
I'll take a look when I find some spare time. If you want to help, feel free to make a PR for this issue.

**Comment by victornoel** [comment]
Why not, where should I start looking in the code for doing that kind of stuff?

**Comment by ferstl** [comment]
Great!
Well, the best point to start are the "Mojos" which represent the different Maven goals of the plugin. There, we need a new Option for the target dependencies. Probably, this is not only useful for the `aggregate` Mojo but also for the other ones.
I suggest, to try solve this issue with an additional `ArtifactFilter` that removes everything that does not point to one of the specified targets. I haven't put much thought into this issue yet. So I am not yet sure if this is solvable with a new filter.

Starting from the Mojos you will come across a `GraphFactory` which is responsible for creating the graph. The entry point into the Maven core libraries is the `GraphBuilderAdapter`. This is an additional layer because I am using two different APIs of the core libraries (tree and graph) which have the same functionality but different interfaces.

**Comment by victornoel** [comment]
Ok, I started looking and I saw you were still using an old version of maven-dependency-tree which has the two APIs (the latest, 3.0, removed the tree API apparently).

I will dig into that a bit and see if I can do something usable ^^

**Comment by ferstl** [comment]
@victornoel Yes, version 3.0 removed the tree API. That is the reason why I haven't updated the version. Issue #7 addressed that.
I expect that there will be an alternative in the future because the `tree` goal of the maven-dependency-plugin is using the tree API as well and I don't think that they drop this goal in future versions of the plugin.

**Comment by victornoel** [comment]
Any reason why you would need the tree API and not only always use the graph API? I thought the graph API would subsume the tree one... just curious!

As for the current issue, a filter won't do I think: we first need to gather the tree (or graph) and then we can know if an artefact is dependent on our target artefact. The filters seem to be used to build the tree/graph itself, so it's too early. I'm continuing my investigation :)

**Comment by ferstl** [comment]
The reason is the `showDuplicate` and `showConflicts` options in the `graph` goal. They are using the `tree` API because these features are not part of the `graph` API.

**Comment by victornoel** [comment]
Ok, I get it :) maybe later it would simple to just rely on aether without going through maven-dependency-tree... I'm not completely sure of its utility for the versions only supporting Maven 3... (well >3.1 actually).

I made a PR :)
