### ISSUE TITLE
-DcutOffDepth=N isn't how cutOffDepth works from the command line

### ISSUE THREAD

**Issue by paul-hammant** [ferstl/depgraph-maven-plugin#99]
The wiki documentation talks of 'cutOffDepth' as a setting but not how to set it, unless I missed it. I tried -DcutOffDepth=1 on the command line, but got a ton of nodes I was not expecting

**Comment by ferstl** [comment]
I guess you are referring to the documentation of the [Target Include Filter](https://github.com/ferstl/depgraph-maven-plugin/wiki/Filtering#target-include-filter). The `cutOffDepth` is not a parameter of the depgraph-maven-plugin. It is only an *internal* counter that is used to construct dependency graphs when the `targetIncludes` parameter is set (this will construct a graph that contains only the paths to the dependencies matching the parameter).
I don't think that a `cutOffDepth` parameter is very useful for the plugin, because it would omit dependencies more or less randomly. I suggest you try some of the various filters (includes/excludes, transitiveIncludes/transitiveExcludes, targetIncludes) to reduce the nodes in your graph. These filters are quite powerful and can reduce the nodes significantly. There is also an entry in the [FAQ](https://github.com/ferstl/depgraph-maven-plugin#faq) about that topic.

**Comment by paul-hammant** [comment]
I'd have to know which groupID/artifactIDs to exclude, then. OK
